### ISSUE TITLE
search by date

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#407]
When the user types 3 or 4 digits (and only that) in the search box, a new option "date" should be available. It uses the same system as other types of queries, there's a [type count](http://purl.bdrc.io/query/table/countDateTypes?GY_RES=1747), and the per-entity requests for instance [works associated with 1747](http://purl.bdrc.io/lib/dateWorks?GY_RES=1747)

**Comment by eroux** [comment]
(note that when there are 3 digits, a 0 should be added on the left of the query (years always have 4 digits in xml for some reason)

**Comment by berger-n** [comment]
seems to be workign fine! http://library-dev.bdrc.io/search?date=%221747%22&t=Person&pg=1&f=relation,inc,bdo:PersonBirth
(had to use `ldspdi` not `ldspdi-dev` to make it work here though) 

![image](https://user-images.githubusercontent.com/33383857/107960543-11920000-6fa5-11eb-8c2c-c7df10813f97.png)

---

![image](https://user-images.githubusercontent.com/33383857/107961728-95002100-6fa6-11eb-8d95-c581af859087.png)

**Comment by eroux** [comment]
Very cool, thanks a lot!! There's an issue where the BDRC and TOL records of the same person are presented as different, but it's probably in the data or SPARQL query, I'll take a look tomorrow

**Comment by eroux** [comment]
well, here the results from the query look correct actually... @berger-n any idea why they are not merged? The merging seems to work just fine for the search on name for instance

**Comment by eroux** [comment]
also, let's slightly refine the search bar:
- don't consider a number as a date if it's > 2100
- when a user input can be considered a date, the possibility of it being a date is actually pretty high so let's make it the first possibility in the list

**Comment by berger-n** [comment]
everything's fine now: http://library-dev.bdrc.io/search?date=%221747%22&t=Person&pg=1&f=relation,inc,bdo:PersonBirth
putting date (if <2100) first 

![image](https://user-images.githubusercontent.com/33383857/108071570-2bdfe280-7066-11eb-98e6-22e3d56fa5e0.png)

**Comment by eroux** [comment]
Wonderful, thanks a lot! Let's put that in prod

**Comment by berger-n** [comment]
done
https://library.bdrc.io/search?date=%221892%22&t=Person
https://library.bdrc.io/search?id=%22NGMPP%20E%2F797%2F2%22&t=Instance&s=title

**Comment by berger-n** [comment]
having a closer looker at http://purl.bdrc.io/lib/datePersons?GY_RES=1892&format=json
some events data seem to be missing (like https://purl.bdrc.io/resource/EVFE776E25CE86AF85.ttl regarding death for https://library.bdrc.io/show/bdr:P258)
resulting in birth/death date not displayed on https://library.bdrc.io/search?date=%221892%22&t=Person&pg=1&f=relation,inc,bdo:PersonDeath

**Comment by eroux** [comment]
Great, thanks a lot! I'll look at the data and query, I noticed that in the general query about persons too

**Comment by eroux** [comment]
so, the story is that some events don't reach the results because of the limit of 500 triples we put in the SPARQL query results. I've changed the query a bit so that it sends less useless triples. The dates for this query are back so that's good, but I suspect that for some queries with a bigger number of results we will still encounter the same issue. I think we allow some queries to have a much bigger amount of results, I'm wondering if we pass these queries the `?I_LIM=xxx` argument in the JavaScript code?

**Comment by berger-n** [comment]
I've added `I_LIM=700` to data/id queries

**Comment by berger-n** [comment]
one minor bug to fix here:
- [ ] using keyboard to select date search triggers keyword search

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/

![Kazam_screencast_00012 mp4](https://user-images.githubusercontent.com/33383857/108727399-d48bb780-7528-11eb-88f9-657a2a4dba90.gif)

---

![Kazam_screencast_00013 mp4](https://user-images.githubusercontent.com/33383857/108727559-0270fc00-7529-11eb-8660-781f89127a17.gif)

**Comment by eroux** [comment]
great, thanks!
